baseURL = 'https://peter-ellinger-blog.com'
languageCode = 'en-us'
title = 'Peter Ellinger'
theme = 'PaperMod'

[params]
  description = "Peter Ellinger blog, contains many of Professor Ellinger's personal works and stories"
  author = "Peter Ellinger"

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadcrumbs = true
  ShowToc = true
  mainSections = []
  enableRobotsTXT = true
  TocSide = 'left'
  TocOpen = true
  env = "production"  # for search

  [params.fuseOpts]  # for search
  isCaseSensitive = false
  shouldSort = true
  includeMatches = false
  threshold = 0.3
  keys = ["title", "summary", "content"]

[outputs]
  home = ["HTML", "RSS", "JSON"] 

[menu]
  [[menu.main]]
    name = "Novels"
    url = "/novels/"
    weight = 1

  [[menu.main]]
    name = "Novellas"
    url = "/novellas/"
    weight = 2

  [[menu.main]]
    name = "Legal Episodes"
    url = "/legal-episodes/"
    weight = 3

  [[menu.main]]
    name = "Short Stories"
    url = "/short-stories/"
    weight = 4

  [[menu.main]]
    name = "Essays"
    url = "/essays/"
    weight = 5

  [[menu.main]]
    name = "About Me"
    url = "/about-me/"
    weight = 10

  [[menu.main]]
    identifier = "search"
    name = "🔍"
    url = "search/"
    weight = 11

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
