baseURL = 'https://breaddcrumbss.github.io/peter-blog/'
languageCode = 'en-us'
title = 'My Collection'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadcrumbs = true
  ShowToc = true

[menu]
  [[menu.main]]
    name = "Novels"
    url = "/novels/"
    weight = 1

  [[menu.main]]
    name = "Novellas"
    url = "/novellas/"
    weight = 2

  [[menu.main]]
    name = "About Me"
    url = "/about-me/"
    weight = 10

[caches]
  [caches.images]
    dir = ':cacheDir/images'
