baseURL = 'https://peter-ellinger-blog.com'
languageCode = 'en-us'
title = 'Peter Ellinger'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadcrumbs = true
  ShowToc = true
  mainSections = []
  enableRobotsTXT = true
  TocSide = 'left'
  TocOpen = true

[menu]
  [[menu.main]]
    name = "Novels"
    url = "/novels/"
    weight = 1

  [[menu.main]]
    name = "Novellas"
    url = "/novellas/"
    weight = 2

  [[menu.main]]
    name = "About Me"
    url = "/about-me/"
    weight = 10

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
